### ISSUE TITLE
Some of the tests are failed

### ISSUE THREAD

**Issue by NastLen** [DB-Student-Repos/r08-01-grep-NastLen#1]
@dominikb1888 

Could you please give me some advice of how I can modify my script

**Comment by dominikb1888** [comment]
I'll check after the test suite has run :-)

**Comment by NastLen** [comment]
I fixed the -n flag. The problem was in the formatting function 😸

**Comment by dominikb1888** [comment]
So... One set of tests is about checking multiple files. Perhaps multiple files come as a different data structure. Currently you only look at lines, maybe you need lines in file as a an idea.

The other tests yield at different combinations of flags. Some of the logic does not seem right yet. 

Nothing where I have a direct solution. Only advice: clean your code and experiment more.

**Comment by dominikb1888** [comment]
> I fixed the -n flag. The problem was in the formatting function 😸

Congratulations 🎉

**Comment by dominikb1888** [comment]
@NastLen If you are still interested in this challenge, here's a good solution using method chaining and match statements: https://exercism.org/tracks/rust/exercises/grep/solutions?order=highest_reputation&amp;page=5

The advantage is: With the Boolean tuples as conditions you are close to truth tables and can make sure you covered all options. In addition the top level structure is very clear. If it is directly more readable is another question.
